import { useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import { useClientConfig } from '../hooks/use-client-config';
import styles from '../styles/Home.module.css';

const Home = () => {
  const { clientConfig } = useClientConfig();
  const fetchFn = async () => (await fetch(clientConfig.NEXT_PUBLIC_API_URL)).json();
  const { data: apiData } = useQuery({ queryKey: ['api-data'], queryFn: fetchFn, enabled: !!clientConfig });

  return (
    // prettier-ignore
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Greg&apos;s config PoC!
        </h1>

        <hr style={{ margin: '2rem auto',width: '25%' }}/>

        <div>
          <p>
            Run demo using: <strong><code>NEXT_PUBLIC_API_URL=https://reqres.in/api/users npm run dev</code></strong><br/>
            or <strong><code>NEXT_PUBLIC_API_URL=https://reqres.in/api/users/1 npm run dev</code></strong>.
          </p>

          {clientConfig &&
            <>
              <strong>Your dynamic runtime config is:</strong>
              <pre>{JSON.stringify(clientConfig, null, 2)}</pre>
            </>
          }
          {apiData &&
            <>
              <strong>Your API data is:</strong>
              <pre>{JSON.stringify(apiData, null, 2)}</pre>
            </>
          }
        </div>

      </main>
    </div>
  );
};

export default Home;
