import { useQuery } from '@tanstack/react-query'
import type { NextPage } from 'next'
import Head from 'next/head'
import useClientConfig from '../hooks/use-client-config'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { clientConfig } = useClientConfig()

  const { data: apiData } = useQuery(['api-data'], async () => {
    return (await fetch(clientConfig.NEXT_PUBLIC_API_URL)).json()
  }, { enabled: !!clientConfig })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Greg&apos;s config PoC!
        </h1>

        {clientConfig &&
          <div className={styles.description} style={{ textAlign: 'left' }}>
            Your dynamic config is: <pre>{JSON.stringify(clientConfig, null, 2)}</pre>
          </div>
        }

        {apiData &&
          <div className={styles.description} style={{ textAlign: 'left' }}>
            Your API data is: <pre>{JSON.stringify(apiData, null, 2)}</pre>
          </div>
      }
      </main>
    </div>
  )
}

export default Home
